In [6]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [44]:
df = pd.read_csv("titanic.csv")

- SimpleImputer b/c we have missing values
- OneHotEncoding b/c we have  categorical data
- MinMaxScalar for scaling
- DecisionTreeClassifier for prediction

In [45]:
# remove columns that we do not need
df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"],inplace=True)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

## Train Test split

We need our model to predict if the person is going to live or not

We drop survived from x(input,independent) and take all others columns and in y then we put it again as output(dependent)

Why is train–test split important?

Without split:
 - Model memorizes answers 
 - Gives fake high accuracy
 - Fails on real data

With split:
 - Model learns patterns 
 - Honest performance check
 - Works in real life

In [46]:
# test_size=0.2 → 20% data for testing, 80% data for training
# random_state=0 → same split every time (for consistency)

X_train, X_test, y_train, y_test  = train_test_split(df.drop(columns=['Survived']),
                                                     df['Survived'],
                                                     test_size=0.2,
                                                     random_state=42
)

In [16]:
X_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [17]:
y_train.head(2)

331    0
733    0
Name: Survived, dtype: int64

In [18]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [47]:
# Apply imputation

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy="most_frequent")

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

- Imputation means: Filling missing data (NaN values) instead of deleting rows.

- SimpleImputer() → tool from sklearn to fill missing values
 - Default strategy = mean

In [48]:
X_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25.        ],
       [24.        ],
       [22.        ],
       [ 0.92      ],
       [24.        ],
       [26.        ],
       [34.        ],
       [21.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [22.        ],
       [62.        ],
       [18.        ],
       [42.        ],
       [57.        ],
       [19.        ],
       [42.        ],
       [29.49884615],
       [20.        ],
       [34.5       ],
       [28.        ],
       [29.49884615],
       [23.        ],
       [22.        ],
       [52.        ],
       [30.        ],
       [36.5       ],
       [29.49884615],
       [22.        ],
       [50.        ],
       [27.        ],
       [22.        ],
       [51.        ],
       [36.        ],
       [29.        ],
       [22.        ],
       [50.        ],
       [40.        ],
       [27.        ],
       [29.49884615],
       [65.        ],
       [17.        ],
       [28.        ],
       [ 4.        ],
       [29.49884615],
       [ 1.        ],
       [36.        ],
       [43.        ],
       [38.        ],
       [31.        ],
       [29.        ],
       [18.        ],
       [29.49884615],
       [39.        ],
       [39.        ],
       [26.        ],
       [20.        ],
       [29.49884615],
       [49.        ],
       [23.        ],
       [ 1.        ],
       [29.49884615],
       [29.49884615],
       [ 3.        ],
       [ 4.        ],
       [19.        ],
       [40.5       ],
       [ 1.        ],
       [29.49884615],
       [21.        ],
       [54.        ],
       [29.49884615],
       [25.        ],
       [26.        ],
       [22.        ],
       [31.        ],
       [49.        ],
       [19.        ],
       [24.        ],
       [16.        ],
       [25.        ],
       [39.        ],
       [47.        ],
       [60.        ],
       [24.        ],
       [29.49884615],
       [27.        ],
       [29.49884615],
       [38.        ],
       [44.        ],
       [21.        ],
       [24.        ],
       [45.        ],
       [ 8.        ],
       [ 8.        ],
       [29.49884615],
       [32.        ],
       [50.        ],
       [21.        ],
       [50.        ],
       [23.        ],
       [32.        ],
       [29.49884615],
       [21.        ],
       [29.49884615],
       [25.        ],
       [15.        ],
       [31.        ],
       [25.        ],
       [54.        ],
       [28.        ],
       [38.        ],
       [41.        ],
       [33.        ],
       [52.        ],
       [16.        ],
       [20.        ],
       [ 9.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [54.        ],
       [26.        ],
       [60.        ],
       [29.49884615],
       [44.        ],
       [20.        ],
       [29.49884615],
       [16.        ],
       [43.        ],
       [17.        ],
       [37.        ],
       [62.        ],
       [ 8.        ],
       [32.        ],
       [20.        ],
       [28.        ],
       [21.        ],
       [37.        ],
       [17.        ],
       [29.49884615],
       [46.        ],
       [29.49884615],
       [24.        ],
       [29.        ],
       [56.        ],
       [31.        ],
       [29.49884615],
       [32.        ],
       [33.        ],
       [59.        ],
       [58.        ],
       [29.49884615],
       [ 3.        ],
       [29.49884615],
       [16.        ],
       [45.        ],
       [43.        ],
       [30.        ],
       [28.5       ],
       [24.        ],
       [30.        ],
       [36.        ],
       [25.        ],
       [29.49884615],
       [50.        ],
       [ 0.75      ],
       [24.        ],
       [24.        ],
       [35.        ],
       [30.        ],
       [23.        ],
       [29.49884615],
       [27.        ],
       [55.        ],
       [35.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [23.        ],
       [29.49884615],
       [23.        ],
       [51.        ],
       [33.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [14.        ],
       [54.        ],
       [15.        ],
       [22.        ],
       [27.        ],
       [29.49884615],
       [29.49884615],
       [28.        ],
       [39.        ],
       [ 2.        ],
       [24.        ],
       [32.        ],
       [45.5       ],
       [ 8.        ],
       [26.        ],
       [29.        ],
       [45.        ],
       [36.        ],
       [29.49884615],
       [ 4.        ],
       [16.        ],
       [58.        ],
       [40.5       ],
       [25.        ],
       [29.49884615],
       [51.        ],
       [29.49884615],
       [17.        ],
       [29.49884615],
       [40.        ],
       [25.        ],
       [47.        ],
       [29.49884615],
       [44.        ],
       [23.        ],
       [18.        ],
       [29.        ],
       [12.        ],
       [11.        ],
       [22.        ],
       [19.        ],
       [22.        ],
       [33.        ],
       [56.        ],
       [ 1.        ],
       [22.        ],
       [29.49884615],
       [29.49884615],
       [ 7.        ],
       [ 4.        ],
       [70.5       ],
       [18.        ],
       [20.        ],
       [24.        ],
       [29.49884615],
       [34.        ],
       [29.49884615],
       [31.        ],
       [30.        ],
       [18.        ],
       [ 9.        ],
       [39.        ],
       [33.        ],
       [70.        ],
       [24.        ],
       [58.        ],
       [21.        ],
       [17.        ],
       [28.        ],
       [24.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [18.        ],
       [ 2.        ],
       [34.        ],
       [ 3.        ],
       [58.        ],
       [32.        ],
       [31.        ],
       [29.49884615],
       [27.        ],
       [11.        ],
       [23.        ],
       [40.        ],
       [29.49884615],
       [28.        ],
       [28.        ],
       [29.49884615],
       [19.        ],
       [30.        ],
       [20.        ],
       [28.        ],
       [36.        ],
       [29.49884615],
       [24.        ],
       [28.5       ],
       [24.        ],
       [42.        ],
       [54.        ],
       [25.        ],
       [ 7.        ],
       [25.        ],
       [27.        ],
       [24.        ],
       [29.49884615],
       [28.        ],
       [19.        ],
       [22.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [50.        ],
       [ 3.        ],
       [29.49884615],
       [18.        ],
       [18.        ],
       [44.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [16.        ],
       [29.49884615],
       [22.        ],
       [ 4.        ],
       [29.49884615],
       [24.        ],
       [30.        ],
       [29.        ],
       [24.        ],
       [45.        ],
       [32.        ],
       [21.        ],
       [35.        ],
       [29.49884615],
       [29.49884615],
       [36.        ],
       [41.        ],
       [23.        ],
       [34.        ],
       [29.49884615],
       [29.49884615],
       [15.        ],
       [29.49884615],
       [18.        ],
       [30.        ],
       [32.        ],
       [ 4.        ],
       [ 2.        ],
       [29.49884615],
       [29.49884615],
       [48.        ],
       [31.        ],
       [47.        ],
       [26.        ],
       [ 9.        ],
       [19.        ],
       [29.49884615],
       [22.        ],
       [29.49884615],
       [28.        ],
       [24.        ],
       [17.        ],
       [29.49884615],
       [29.49884615],
       [21.        ],
       [51.        ],
       [ 3.        ],
       [ 0.75      ],
       [29.49884615],
       [34.        ],
       [18.        ],
       [44.        ],
       [29.49884615],
       [29.49884615],
       [37.        ],
       [21.        ],
       [36.        ],
       [32.        ],
       [29.49884615],
       [26.        ],
       [80.        ],
       [55.5       ],
       [60.        ],
       [29.49884615],
       [18.        ],
       [14.5       ],
       [19.        ],
       [ 4.        ],
       [33.        ],
       [21.        ],
       [10.        ],
       [47.        ],
       [ 2.        ],
       [29.        ],
       [22.        ],
       [28.        ],
       [29.49884615],
       [26.        ],
       [33.        ],
       [27.        ],
       [27.        ],
       [34.        ],
       [29.49884615],
       [30.        ],
       [30.        ],
       [29.49884615],
       [29.49884615],
       [53.        ],
       [32.        ],
       [52.        ],
       [52.        ],
       [39.        ],
       [ 2.        ],
       [44.        ],
       [51.        ],
       [39.        ],
       [46.        ],
       [17.        ],
       [30.        ],
       [ 9.        ],
       [27.        ],
       [21.        ],
       [29.49884615],
       [26.        ],
       [ 3.        ],
       [48.        ],
       [36.        ],
       [29.49884615],
       [32.5       ],
       [33.        ],
       [22.        ],
       [19.        ],
       [74.        ],
       [42.        ],
       [40.        ],
       [35.        ],
       [24.        ],
       [39.        ],
       [32.5       ],
       [ 1.        ],
       [34.        ],
       [64.        ],
       [25.        ],
       [29.49884615],
       [ 1.        ],
       [45.        ],
       [31.        ],
       [21.        ],
       [25.        ],
       [15.        ],
       [26.        ],
       [30.        ],
       [24.        ],
       [35.        ],
       [70.        ],
       [29.49884615],
       [21.        ],
       [18.        ],
       [29.49884615],
       [ 1.        ],
       [29.49884615],
       [26.        ],
       [25.        ],
       [29.49884615],
       [20.        ],
       [54.        ],
       [22.        ],
       [59.        ],
       [54.        ],
       [27.        ],
       [31.        ],
       [22.        ],
       [33.        ],
       [ 6.        ],
       [ 5.        ],
       [39.        ],
       [24.5       ],
       [54.        ],
       [29.49884615],
       [29.49884615],
       [30.        ],
       [29.49884615],
       [35.        ],
       [21.        ],
       [32.        ],
       [16.        ],
       [22.        ],
       [29.49884615],
       [38.        ],
       [29.49884615],
       [25.        ],
       [33.        ],
       [29.49884615],
       [18.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [ 0.42      ],
       [26.        ],
       [41.        ],
       [48.        ],
       [48.        ],
       [48.        ],
       [ 4.        ],
       [39.        ],
       [33.        ],
       [29.        ],
       [49.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [61.        ],
       [18.        ],
       [18.        ],
       [ 0.67      ],
       [32.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [16.        ],
       [31.        ],
       [48.        ],
       [22.        ],
       [13.        ],
       [32.        ],
       [28.        ],
       [46.        ],
       [28.        ],
       [42.        ],
       [35.        ],
       [ 2.        ],
       [31.        ],
       [29.49884615],
       [29.49884615],
       [19.        ],
       [20.        ],
       [14.        ],
       [34.        ],
       [29.49884615],
       [29.49884615],
       [51.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [28.        ],
       [25.        ],
       [19.        ],
       [35.        ],
       [35.        ],
       [ 9.        ],
       [20.        ],
       [42.        ],
       [30.        ],
       [29.49884615],
       [21.        ],
       [47.        ],
       [25.        ],
       [16.        ],
       [45.        ],
       [38.        ],
       [56.        ],
       [29.49884615],
       [31.        ],
       [30.        ],
       [29.49884615],
       [14.        ],
       [16.        ],
       [40.        ],
       [55.        ],
       [19.        ],
       [45.        ],
       [36.        ],
       [27.        ],
       [49.        ],
       [41.        ],
       [19.        ],
       [33.        ],
       [27.        ],
       [29.49884615],
       [35.        ],
       [29.        ],
       [30.        ],
       [34.        ],
       [29.        ],
       [19.        ],
       [35.        ],
       [29.49884615],
       [40.        ],
       [62.        ],
       [25.        ],
       [26.        ],
       [18.        ],
       [34.        ],
       [48.        ],
       [28.        ],
       [24.        ],
       [17.        ],
       [38.        ],
       [29.49884615],
       [40.        ],
       [22.        ],
       [ 2.        ],
       [28.        ],
       [18.        ],
       [28.        ],
       [19.        ],
       [29.49884615],
       [60.        ],
       [20.        ],
       [45.        ],
       [29.49884615],
       [24.        ],
       [29.49884615],
       [29.49884615],
       [39.        ],
       [26.        ],
       [24.        ],
       [36.        ],
       [37.        ],
       [29.49884615],
       [28.        ],
       [19.        ],
       [43.        ],
       [25.        ],
       [47.        ],
       [16.        ],
       [ 0.83      ],
       [22.        ],
       [19.        ],
       [28.        ],
       [14.        ],
       [36.        ],
       [29.        ],
       [42.        ],
       [29.49884615],
       [27.        ],
       [29.        ],
       [ 5.        ],
       [22.        ],
       [29.49884615],
       [30.        ],
       [62.        ],
       [34.        ],
       [28.        ],
       [29.49884615],
       [44.        ],
       [45.        ],
       [19.        ],
       [18.        ],
       [31.        ],
       [29.49884615],
       [21.        ],
       [25.        ],
       [32.        ],
       [30.        ],
       [40.        ],
       [33.        ],
       [36.        ],
       [47.        ],
       [34.        ],
       [19.        ],
       [29.49884615],
       [50.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [35.        ],
       [35.        ],
       [18.        ],
       [16.        ],
       [21.        ],
       [29.49884615],
       [41.        ],
       [14.        ],
       [21.        ]])

In [49]:
X_train_embarked

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['Q'],
       ['Q'],
       ['C'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['Q'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S']], dtype=object)

## One Hot Encoding

- Now we have two columns Age and Embarked they in both are categorical data. So we need to transform them into numerical data so use onehotencoding

- Computers work with numbers, not words. But columns like Sex and Embarked contain words (e.g., male/female, port names). So we must convert words into numbers.

- Why is handle_unknown=“ignore” used?
 - If a new value appears (something not seen before). The program won’t crash

In [50]:
ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

x_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

x_test_sex = ohe_sex.fit_transform(X_test[['Sex']])
x_test_embarked = ohe_embarked.fit_transform(X_test_embarked)

In [51]:
x_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [52]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])

In [53]:
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [54]:
X_train_rem

     Pclass  SibSp  Parch      Fare
331       1      0      0   28.5000
733       2      0      0   13.0000
382       3      0      0    7.9250
704       3      1      0    7.8542
813       3      4      2   31.2750
..      ...    ...    ...       ...
106       3      0      0    7.6500
270       1      0      0   31.0000
860       3      2      0   14.1083
435       1      1      2  120.0000
102       1      0      1   77.2875

[712 rows x 4 columns]

In [56]:
X_train_transformed = np.concatenate([X_train_rem, X_train_age, x_train_embarked, x_train_sex], axis=1)
X_test_transformed = np.concatenate([X_test_rem, X_test_age, x_test_embarked, x_test_sex], axis=1)

In [57]:
X_train_transformed

array([[1., 0., 0., ..., 1., 0., 1.],
       [2., 0., 0., ..., 1., 0., 1.],
       [3., 0., 0., ..., 1., 0., 1.],
       ...,
       [3., 2., 0., ..., 1., 0., 1.],
       [1., 1., 2., ..., 1., 1., 0.],
       [1., 0., 1., ..., 1., 0., 1.]])

## Decision Tree Classifier

In [65]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [66]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1])

In [69]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7821229050279329

## Storing

In [71]:
import pickle

In [76]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl', 'wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl', 'wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))

# Without Using the ML pipeline

In [89]:
import pickle
import numpy as np

In [102]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [103]:
# Assuming user input
# pclass/gender/age/sibsp/parch/Fare/Embarked
test_input = np.array([2,'male',31,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [92]:
test_input

array([[2, 'male', 31, 0, 0, 10.5, 'S']], dtype=object)

In [104]:
# Preprocess
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, 1))
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))
test_input_age = test_input[:, 2].reshape(1, 1)
test_input_rem = test_input[:, [0, 3, 4, 5]]  # pclass, sibsp, parch, fare

/Users/mycomputer/.pyenv/versions/3.12.3/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [105]:
# Combine
test_input_rem = test_input[:, [0, 3, 4, 5]]  # pclass, sibsp, parch, fare

test_input_transformed = np.concatenate([
    test_input_rem,
    test_input_age,
    test_input_embarked,
    test_input_sex
], axis=1)

In [106]:
test_input_transformed.shape

(1, 10)

In [108]:
prediction = clf.predict(test_input_transformed)
print('Survived' if prediction[0] == 1 else 'Not Survived')

Survived

# Using ML Pipeline

In [109]:
import numpy as np
import pandas as pd

In [121]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [111]:
df = pd.read_csv("titanic.csv")

In [112]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In a pipeline, we first preprocess the data, then apply transformations like encoding and scaling, and finally train the model.
Pipeline ensures the same steps are applied to both training and testing data and prevents data leakage.

We have missing data in Age & Embarked columns

## Steps of Pipeline

- Train Test split 
- impute(fill) missing values by using one column transformer.
- (OHE) is output of step 1 send to second column transformer. Work of this column is to ohe of two columns(sex & embarked).
- scaling because all columns comes in similar numerical range.
- feature Selection (means we take 5 best columns(features)
- Decision Tree (we train model in this step by using decision tree that will give me output)

In [113]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"],inplace=True)
# inplace means changes will be applied to original dataframe. 
# If we do inplace false a new dataframe will be created and original dataframe will remain same.

In [114]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [115]:
# Step 1: Test train split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=["Survived"]),
                                                   df["Survived"], test_size=0.2, random_state=42)

# random state is used to get same split every time we run the code. 42 is just a number we can use any integer.

In [116]:
X_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [117]:
y_train.sample(5)

826    0
392    0
609    1
747    1
583    0
Name: Survived, dtype: int64

In [122]:
#  Step 2 : Imputation transformer

trf1 = ColumnTransformer(
    [
        ("impute_age", SimpleImputer(), [2]), #  2 is index value of age column 
        # its a good strategy  to add index values instead of column names 
        # because in further steps if we do one hot encoding column names will change but index values will remain same
        ("impute_embarked", SimpleImputer(strategy="most_frequent"), [6]) # 6 is column name
    ],
    remainder="passthrough"
)

# passthrough means all other columns except the mentioned columns will remain the same
# most frequent means mode value will be used for imputation

column transformer is used to apply different transformations to different columns.

In [126]:
# Step 3: # One hot encoding 
# converting categorical values into numerical values by creating new columns for each category.

trf2 = ColumnTransformer(
    [
        ("one_sex_embarked", OneHotEncoder(sparse_output=False, handle_unknown="ignore"), [1,6])
    ],
    remainder="passthrough"
    
)

In [127]:
# Step 4: # Scaling
# converting values into a specific range. Here we are using min max scaler which converts values into range of 0 to 1.

trf3 = ColumnTransformer(
    [
        ("scale",MinMaxScaler(),slice(0,10)) # slice(4,12) means columns from index 4 to index 11
    ]
)

# Here we use minmiaz scaling not standard scaler because min max scaler keeps the distribution of data same
# whereas standard scaler changes the distribution of data. 

# In feature selection as we do we use minmax scaling because feature selection techniques are sensitive to distribution of data.

# we apply minmax scaling on all column if we want to apply on specific columns we can use index values instead of slice.

# We write 10 in slicing because after one hot encoding total 10 columns will be there.

In [129]:
# Step 5: # Feature Selection

# Feature selection means selecting best features from the dataset.

trf4 = SelectKBest(score_func=chi2, k=8) # k is number of best features to select

In [130]:
# Step 6: # Train the model
trf5 = DecisionTreeClassifier()
# decision tree classifier means we are using decision tree algorithm for classification.

In [132]:
pipe = Pipeline([
    ("trf1", trf1),
    ("trf2", trf2),
    ("trf3", trf3),
    ("trf4", trf4),
    ("trf5", trf5)
])

# Pipeline is used to combine multiple steps into one. Here we are combining all the transformers and the classifier into one pipeline.
# here we pass list o f tuples where each tuple contains name of the step and the transformer or classifier object.

# Alternate syntax
# pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [133]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('one_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=8, score_func=<function chi2 at 0x136c87920>)),
                ('trf5', DecisionTreeClassifier())])

## Explore the pipeline

In [136]:
pipe.named_steps

{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'trf2': ColumnTransformer(remainder='passthrough',
                   transformers=[('one_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'trf3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'trf4': SelectKBest(k=8, score_func=<function chi2 at 0x136c87920>),
 'trf5': DecisionTreeClassifier()}

In [137]:
pipe.named_steps["trf1"].transformers_[0][1].statistics_  # to see the imputed values for age

array([29.49884615])

In [138]:
# Display pipline 

from sklearn import set_config
set_config(display="diagram")

In [139]:
y_pred = pipe.predict(X_test)

In [140]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

## GridSearch using pipleline

In [141]:
params = {
    "trf5__max_depth": [1,2,3,4,5,None],
}

In [142]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, param_grid=params, cv=5, scoring="accuracy")
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('trf2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('one_sex_embarked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('trf3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('trf4',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x136c87920>)),
                                       ('trf5', DecisionTreeClassifier())]),
             param_grid={'trf5__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [143]:
grid.best_score_

0.6391214419383433

In [144]:
grid.best_params_

{'trf5__max_depth': 2}

### Exporting the Pipeline

In [145]:
import numpy as np
import pickle

In [147]:
import pickle
pickle.dump(pipe, open("titanic_pipe.pkl","wb"))

### Predict-using-pipeline

In [1]:
import numpy as np
import pickle

In [2]:
pipe = pickle.load(open("titanic_pipe.pkl","rb"))

In [3]:
test_input2 = np.array([2, "male", 31, 0,0,10.5,"S"],dtype=object).reshape(1,7)

In [4]:
pipe.predict(test_input2)

/Users/mycomputer/.pyenv/versions/3.12.3/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/Users/mycomputer/.pyenv/versions/3.12.3/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

array([0])