In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df = pd.read_csv("covid_toy.csv")

In [6]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"], test_size=0.2)

In [11]:
X_train

    age  gender  fever   cough       city
24   13  Female  100.0  Strong    Kolkata
68   54  Female  104.0  Strong    Kolkata
86   25    Male  104.0    Mild  Bangalore
57   49  Female   99.0  Strong  Bangalore
99   10  Female   98.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
72   83  Female  101.0    Mild    Kolkata
33   26  Female   98.0    Mild    Kolkata
20   12    Male   98.0  Strong  Bangalore
79   48  Female  103.0    Mild    Kolkata
47   18  Female  104.0    Mild  Bangalore

[80 rows x 5 columns]

## Common - Without column Transformer

In [16]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [ ]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape